wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 20
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error
momentum:
  value: 0.9
num_layers:
  value: 3
optimizer:
  value: nadam
output_activation:
  value: softmax
weight_decay:
  value: 0.05
weight_init:
  value: random
